name: Build & Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v3
    
    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        cache: 'npm'

    - name: Instalar pacotes NPM
      run: npm ci
    
    - name: Construir projeto
      run: npm run build
    
    - name: Executar testes
      run: npm run test

    - name: Salvar artefatos para produção
      uses: actions/upload-artifact@v3
      with:
        name: arquivos-producao
        path: ./build
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Baixar artefatos
      uses: actions/download-artifact@v3
      with:
        name: arquivos-producao
        path: ./build

    - name: Realizar deploy para gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build